name: CI
on:
  push: {branches:  [main] }
  pull_request: {branches: [main] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm', cache-dependency-path: api/package-lock.json }
      - run: npm install
        working-directory: api
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "ENV=$APP_ENV ; token len =${DOCKER_TOKEN}"
        env:
          APP_ENV: ${{ vars.APP_ENV }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  test:
    needs: build
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: api} }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm', cache-dependency-path: api/package-lock.json }
      - run: npm install && npm test
        working-directory: api
      - run: mkdir -p coverage && NODE_V8_COVERAGE=coverage node --test --experimental-test-coverage
        working-directory: api
      - uses: actions/upload-artifact@v4
        with: { name: coverage, path: api/coverage }
        if: always()
